---
- name: Setup undercloud upgrade facts
  set_fact:
    _upgrade_cmd: >-
      {{ openstack_bin }} undercloud upgrade
      {{ tripleo_undercloud_upgrade_force_stack_update | ternary("--force-stack-update", '') }}
      {{ tripleo_undercloud_upgrade_no_validations | ternary("--no-validations", '') }}
      {{ tripleo_undercloud_upgrade_inflight_validations | ternary("--inflight-validations", '') }}
      {{ tripleo_undercloud_upgrade_dry_run | ternary("--dry-run", '') }}
      {{ tripleo_undercloud_upgrade_yes | ternary("--yes", '') }}
      {{ tripleo_undercloud_upgrade_log_output | ternary((">" ~ tripleo_undercloud_upgrade_log), '') }}
      {{ tripleo_undercloud_upgrade_log_combine | ternary("2>&1", '') }}

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_undercloud_upgrade_log }}"
  when: tripleo_undercloud_upgrade_log_output|bool

- name: Show the underclound upgrade command
  debug:
    var: _upgrade_cmd
  when: tripleo_undercloud_upgrade_debug|bool

- name: undercloud upgrade
  shell: "{{ _upgrade_cmd }}"  # noqa 305
  args:
    chdir: "{{ tripleo_undercloud_upgrade_home_dir }}"
    warn: false
  async: "{{ tripleo_undercloud_upgrade_timeout }}"
  poll: "{{ tripleo_undercloud_upgrade_poll }}"
  register: tripleo_undercloud_upgrade_result
  changed_when: true
