---
# tasks file for tripleo_overcloud_node_bios_configure
- name: Setup overcloud node bios configure command
  set_fact:
    _bios_cmd: >-
      {{ tripleo_overcloud_node_bios_configure_os_cloud | ternary('', "source " ~ tripleo_overcloud_node_bios_configure_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud node bios configure
      {{ tripleo_overcloud_node_bios_configure_node_uuids | join(' ') }}
      {{ tripleo_overcloud_node_bios_configure_all_manageable | ternary('--all-manageable', '') }}
      {{ tripleo_overcloud_node_bios_configure_configuration | ternary('--configuration ' ~ tripleo_overcloud_node_bios_configure_configuration, '') }}

    _bios_env:
      OS_CLOUD: "{{ tripleo_overcloud_node_bios_configure_os_cloud }}"

- name: Show debug information
  when: tripleo_overcloud_node_bios_configure_debug|bool
  block:
    - name: Show the node bios configuration command
      debug:
        var: _bios_cmd

    - name: Show the node bios configuration environment
      debug:
        var: _bios_env

- name: Configure node bios
  shell: "{{ _bios_cmd }}"  # noqa 305
  environment: "{{ _bios_env }}"
  register: tripleo_overcloud_node_bios_configure_result
  changed_when: true

- name: Set output fact
  set_fact:
    tripleo_overcloud_node_bios_configure_output: "{{ tripleo_overcloud_node_bios_configure_result.stdout }}"
