---
# tasks file for tripleo_overcloud_node_clean
- name: Setup overcloud node clean command
  set_fact:
    _clean_cmd: >-
      {{ tripleo_overcloud_node_clean_os_cloud | ternary('', "source " ~ tripleo_overcloud_node_clean_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud node clean
      {{ tripleo_overcloud_node_clean_node_uuids | join(' ') }}
      {{ tripleo_overcloud_node_clean_all_manageable | ternary('--all-manageable', '') }}
      {{ tripleo_overcloud_node_clean_provide | ternary('--provide', '') }}

- name: Show the node clean command
  debug:
    var: _clean_cmd
  when: tripleo_overcloud_node_clean_debug|bool

- name: Clean node
  shell: "{{ _clean_cmd }}"  # noqa 305
  register: tripleo_overcloud_node_clean_result
  changed_when: true

- name: Set output fact
  set_fact:
    tripleo_overcloud_node_clean_output: "{{ tripleo_overcloud_node_clean_result.stdout }}"
