---
# tasks file for tripleo_overcloud_node_configure
- name: Setup overcloud node configure command
  set_fact:
    _configure_cmd: >-
      {{ tripleo_overcloud_node_configure_os_cloud | ternary('', "source " ~ tripleo_overcloud_node_configure_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud node configure
      {{ tripleo_overcloud_node_configure_node_uuids | join(' ') }}
      {{ tripleo_overcloud_node_configure_all_manageable | ternary('--all-manageable', '') }}
      {{ tripleo_overcloud_node_configure_deploy_kernel | ternary('--deploy-kernel ' ~ tripleo_overcloud_node_configure_deploy_kernel, '') }}
      {{ tripleo_overcloud_node_configure_deploy_ramdisk | ternary('--deploy-ramdisk ' ~ tripleo_overcloud_node_configure_deploy_ramdisk, '') }}
      {{ tripleo_overcloud_node_configure_instance_boot_option | ternary('--instance-boot-option '
      ~ tripleo_overcloud_node_configure_instance_boot_option, '') }}
      {{ tripleo_overcloud_node_configure_root_device | ternary('--root-device ' ~ tripleo_overcloud_node_configure_root_device, '') }}
      {{ tripleo_overcloud_node_configure_root_device_minimum_size | ternary('--root-device-minimum-size '
      ~ tripleo_overcloud_node_configure_root_device_minimum_size, '') }}
      {{ tripleo_overcloud_node_configure_overwrite_root_device_hints | ternary('--overwrite-root-device-hints', '') }}


- name: Show the node configure command
  debug:
    var: _configure_cmd
  when: tripleo_overcloud_node_configure_debug|bool

- name: Configure node
  shell: "{{ _configure_cmd }}"  # noqa 305
  register: tripleo_overcloud_node_configure_result
  changed_when: true

- name: Set output fact
  set_fact:
    tripleo_overcloud_node_configure_output: "{{ tripleo_overcloud_node_configure_result.stdout }}"
