---
# defaults file for tripleo-undercloud
tripleo_undercloud_upgrade_debug: false
tripleo_undercloud_upgrade_dry_run: false
tripleo_undercloud_upgrade_force_stack_update: false
tripleo_undercloud_upgrade_home_dir: "{{ ansible_env.HOME }}"
tripleo_undercloud_upgrade_inflight_validations: false
tripleo_undercloud_upgrade_log_combine: true
tripleo_undercloud_upgrade_log_output: true
tripleo_undercloud_upgrade_no_validations: false
tripleo_undercloud_upgrade_timeout: 7200
tripleo_undercloud_upgrade_yes: false
tripleo_undercloud_upgrade_log: "{{ tripleo_undercloud_upgrade_home_dir }}/undercloud_upgrade.log"
