---
# tasks file for tripleo_overcloud_node_introspect
- name: Setup overcloud node introspect command
  set_fact:
    _introspect_cmd: >-
      {{ tripleo_overcloud_node_configure_os_cloud | ternary('', "source " ~ tripleo_overcloud_node_configure_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud node introspect
      {{ tripleo_overcloud_node_introspect_node_uuids | join(' ') }}
      {{ tripleo_overcloud_node_introspect_all_manageable | ternary('--all-manageable', '') }}
      {{ tripleo_overcloud_node_introspect_provide | ternary('--provide', '') }}
      {{ tripleo_overcloud_node_introspect_run_validations | ternary('--run-validations', '') }}
      {{ tripleo_overcloud_node_introspect_concurrency | ternary('--concurrency ' ~ tripleo_overcloud_node_introspect_concurrency, '') }}


- name: Show the node introspect command
  debug:
    var: _introspect_cmd
  when: tripleo_overcloud_node_introspect_debug|bool

- name: Introspect node
  shell: "{{ _introspect_cmd }}"  # noqa 305
  register: tripleo_overcloud_node_introspect_result
  changed_when: true

- name: Set output fact
  set_fact:
    tripleo_overcloud_node_introspect_output: "{{ tripleo_overcloud_node_introspect_result.stdout }}"
