---
# tasks file for tripleo_container_image_show
- name: Setup container image show facts
  set_fact:
    _show_cmd: >-
      {{ openstack_bin }} tripleo container image show
      {{ tripleo_container_image_show_username | ternary('--username $TRIPLEO_IMAGE_SHOW_USERNAME', '') }}
      {{ tripleo_container_image_show_password | ternary('--password $TRIPLEO_IMAGE_SHOW_PASSWORD', '') }}
      {{ tripleo_container_image_show_format | ternary('-f $TRIPLEO_IMAGE_SHOW_FORMAT', '') }}
      {{ tripleo_container_image_show_image }}

- name: Show the container image show command
  debug:
    var: _show_cmd
  when: tripleo_container_image_show_debug|bool

- name: Container image show
  shell: "{{ _show_cmd }}"  # noqa 305
  environment:
    TRIPLEO_IMAGE_SHOW_USERNAME: "{{ tripleo_container_image_show_username | default('') }}"
    TRIPLEO_IMAGE_SHOW_PASSWORD: "{{ tripleo_container_image_show_password | default('') }}"
    TRIPLEO_IMAGE_SHOW_FORMAT: "{{ tripleo_container_image_show_format | default('') }}"
  register: tripleo_container_image_show_result
  changed_when: false

- name: Set output fact
  set_fact:
    tripleo_container_image_show_output: "{{ tripleo_container_image_show_result.stdout }}"
