---
- name: Setup undercloud minion upgrade facts
  set_fact:
    _upgrade_cmd: >-
      {{ openstack_bin }} undercloud minion upgrade
      {{ tripleo_undercloud_minion_upgrade_force_stack_update | ternary("--force-stack-update", '') }}
      {{ tripleo_undercloud_minion_upgrade_no_validations | ternary("--no-validations", '') }}
      {{ tripleo_undercloud_minion_upgrade_dry_run | ternary("--dry-run", '') }}
      {{ tripleo_undercloud_minion_upgrade_yes | ternary("--yes", '') }}
      {{ tripleo_undercloud_minion_upgrade_log_output | ternary((">" ~ tripleo_undercloud_minion_upgrade_log), '') }}
      {{ tripleo_undercloud_minion_upgrade_log_combine | ternary("2>&1", '') }}

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_undercloud_minion_upgrade_log }}"
  when: tripleo_undercloud_minion_upgrade_log_output|bool

- name: Show the underclound minion upgrade command
  debug:
    var: _upgrade_cmd
  when: tripleo_undercloud_minion_upgrade_debug|bool

- name: undercloud minion upgrade
  shell: "{{ _upgrade_cmd }}"  # noqa 305
  args:
    chdir: "{{ tripleo_undercloud_minion_upgrade_home_dir }}"
  async: "{{ tripleo_undercloud_minion_upgrade_timeout }}"
  poll: "{{ tripleo_undercloud_minion_upgrade_poll }}"
  register: tripleo_undercloud_minion_upgrade_result
  changed_when: true
