---
- name: Setup config generate ansible facts
  set_fact:
    _generate_cmd: >-
      {{ tripleo_config_generate_ansible_os_cloud | ternary('', "source " ~ tripleo_config_generate_ansible_rc_file ~ "; ") }}
      openstack tripleo config generate ansible
      {{ tripleo_config_generate_ansible_deployment_user | ternary("--deployment_user " ~ tripleo_config_generate_ansible_deployment_user, '') }}
      {{ tripleo_config_generate_ansible_output_dir | ternary("--output-dir " ~ tripleo_config_generate_ansible_output_dir, '') }}

- name: Show the config generate ansible command
  debug:
    var: _generate_cmd
  when: tripleo_config_generate_ansible_debug|bool

- name: tripleo config generate ansible
  shell: "{{ _generate_cmd }}"  # noqa 305
  args:
    warn: false
  environment:
    OS_CLOUD: "{{ tripleo_config_generate_ansible_os_cloud }}"
  register: tripleo_config_generate_ansible_result
  changed_when: true
