---
# tasks file for tripleo_container_image_prepare_default
- name: Setup container image prepare default facts
  set_fact:
    _prepare_cmd: >-
      openstack tripleo container image prepare default
      {{ tripleo_container_image_prepare_default_output_env_file | ternary('--output-env-file '
      ~ tripleo_container_image_prepare_default_output_env_file, '') }}
      {{ tripleo_container_image_prepare_default_local_push_destination | ternary('--local-push-destination', '') }}

- name: Show the container image push command
  debug:
    var: _prepare_cmd
  when: tripleo_container_image_prepare_default_debug|bool

- name: Container image push
  shell: "{{ _prepare_cmd }}"  # noqa 305
  register: tripleo_container_image_prepare_default_result
  changed_when: true

- name: Set output variable
  set_fact:
    tripleo_container_image_prepare_default_result: "{{ tripleo_container_image_prepare_default_result.stdout }}"
