---
# tasks file for tripleo-container-image-list
- name: Setup container image list facts
  set_fact:
    _list_cmd: >-
      openstack tripleo container image list
      {{ tripleo_container_image_list_username | ternary('--username ' ~ tripleo_container_image_list_username, '') }}
      {{ tripleo_container_image_list_password | ternary('--password ' ~ tripleo_container_image_list_password, '') }}
      {{ tripleo_container_image_list_registry | ternary('--registry ' ~ tripleo_container_image_list_registry, '') }}
      {{ tripleo_container_image_list_format | ternary('-f ' ~ tripleo_container_image_list_format, '') }}

- name: Show the container image list command
  debug:
    var: _list_cmd
  when: tripleo_container_image_list_debug|bool

- name: Container image list
  shell: "{{ _list_cmd }}"  # noqa 305
  register: tripleo_container_image_list_result
  changed_when: false

- name: Set output fact
  set_fact:
    tripleo_container_image_list_output: "{{ tripleo_container_image_list_result.stdout }}"
