---
# tasks file for tripleo-container-image-show
- name: Setup container image show facts
  set_fact:
    _show_cmd: >-
      openstack tripleo container image show
      {{ tripleo_container_image_show_username | ternary('--username ' ~ tripleo_container_image_show_username), '') }}
      {{ tripleo_container_image_show_password | ternary('--password ' ~ tripleo_container_image_show_password, '') }}
      {{ tripleo_container_image_show_format | ternary('-f ' ~ tripleo_container_image_show_format, '') }}
      {{ tripleo_container_image_show_image }}

- name: Show the container image show command
  debug:
    var: _show_cmd
  when: tripleo_container_image_show_debug|bool

- name: Container image show
  shell: "{{ _show_cmd }}"  # noqa 305
  register: tripleo_container_image_show_result
  changed_when: false

- name: Set output fact
  set_fact:
    tripleo_container_image_show_output: "{{ tripleo_container_image_show_result.stdout }}"
